Add migrations to allow user role CRUD on tables.
DataHackIL/ninjathon pull request #40
Opened 2020-02-21 15:28 UTC by wildeyes

Tables: teams and team_members.

2020-02-21 20:10 UTC, shakedlokits approved these changes
LGTM 👍

2020-02-21 20:12 UTC, shakedlokits requested changes
Wait, this migration misses the authentication tables

2020-02-22 20:15 UTC, wildeyes commented
authentication table as in users? it contains those

2020-02-23 05:31 UTC, shakedlokits approved these changes

2020-02-25 16:09 UTC, merged